import pathlib
import unittest


class EmbyOperationsTabFrontendTests(unittest.TestCase):
    def test_live_task_and_stream_markup_escapes_emby_values(self):
        source = pathlib.Path("static/emby_operations.js").read_text(encoding="utf-8")

        for marker in (
            "const safeName = escapeHtml(name);",
            "const safeState = escapeHtml(state);",
            "const safeTaskId = escapeHtml(taskId);",
            "const safeServerId = escapeHtml(serverId);",
            "const safeUser = escapeHtml(user);",
            "const safeDisplayTitle = escapeHtml(displayTitle);",
            "const safeDevice = escapeHtml(entry.device || 'N/D');",
            "const safeState = escapeHtml(entry.state || 'N/D');",
        ):
            self.assertIn(marker, source)

    def test_disabled_servers_have_explicit_status_and_disabled_restart_button(self):
        js_source = pathlib.Path("static/emby_operations.js").read_text(encoding="utf-8")
        template_source = pathlib.Path("templates/partials/emby_operations.html").read_text(encoding="utf-8")
        css_source = pathlib.Path("static/emby.css").read_text(encoding="utf-8")

        self.assertIn("const updateStatusPill = (pill, status = {}) => {", js_source)
        self.assertIn("status.error === 'Server disabilitato'", js_source)
        self.assertIn("pill.classList.toggle('disabled', isDisabled);", js_source)
        self.assertIn('class="status-pill disabled"', template_source)
        self.assertIn('disabled aria-disabled="true"', template_source)
        self.assertIn(".status-pill.disabled", css_source)

    def test_operations_tab_is_split_into_partial_and_dedicated_script(self):
        dashboard_source = pathlib.Path("templates/emby_dashboard.html").read_text(encoding="utf-8")
        partial_source = pathlib.Path("templates/partials/emby_operations.html").read_text(encoding="utf-8")
        widgets_source = pathlib.Path("static/emby_widgets.js").read_text(encoding="utf-8")
        operations_source = pathlib.Path("static/emby_operations.js").read_text(encoding="utf-8")

        self.assertIn('{% include "partials/emby_operations.html" %}', dashboard_source)
        self.assertIn('data-tab-panel="actions"', partial_source)
        self.assertIn("emby_operations.js", dashboard_source)
        self.assertIn("window.octohubsEmbyOperations", operations_source)
        self.assertIn("window.updateStreamPanel = updateStreamPanel;", operations_source)
        self.assertNotIn("startStatusStream", widgets_source)
        self.assertNotIn("button[data-action=\"stop-task\"]", widgets_source)

    def test_operations_tab_exposes_transcode_guard_controls_and_badges(self):
        dashboard_source = pathlib.Path("templates/emby_dashboard.html").read_text(encoding="utf-8")
        partial_source = pathlib.Path("templates/partials/emby_operations.html").read_text(encoding="utf-8")
        guard_source = pathlib.Path("templates/partials/emby_transcode_guard.html").read_text(encoding="utf-8")
        operations_source = pathlib.Path("static/emby_operations.js").read_text(encoding="utf-8")
        css_source = pathlib.Path("static/emby.css").read_text(encoding="utf-8")

        self.assertIn('data-tab="transcode-guard"', dashboard_source)
        self.assertIn('{% include "partials/emby_transcode_guard.html" %}', dashboard_source)
        self.assertNotIn('data-transcode-guard-panel', partial_source)
        self.assertIn('data-tab-panel="transcode-guard"', guard_source)
        self.assertIn('data-transcode-guard-panel', guard_source)
        self.assertIn('transcode-guard-header', guard_source)
        self.assertIn('transcode-guard-header page-card-header', guard_source)
        self.assertIn('transcode-guard-title-block', guard_source)
        self.assertIn('transcode-guard-header-actions page-card-actions', guard_source)
        self.assertIn('transcode-guard-header-switch', guard_source)
        self.assertIn('latest-header page-card-header', dashboard_source)
        self.assertIn('latest-actions page-card-actions', dashboard_source)
        self.assertIn('transcode-guard-state-grid', guard_source)
        self.assertNotIn('transcode-guard-hero', guard_source)
        self.assertNotIn('transcode-guard-title-icon', guard_source)
        self.assertIn('transcode-guard-metric-card', guard_source)
        self.assertIn('form="transcode-guard-form"', guard_source)
        self.assertIn('id="transcode-guard-form"', guard_source)
        self.assertLess(guard_source.index('transcode-guard-title-block'), guard_source.index('Monitora gli stream'))
        self.assertLess(guard_source.index('Monitora gli stream'), guard_source.index('transcode-guard-header-actions'))
        self.assertLess(guard_source.index('transcode-guard-header-switch'), guard_source.index('transcode-guard-state-grid'))
        self.assertNotIn('data-action="transcode-guard-refresh"', guard_source)
        self.assertNotIn('transcode-guard-state-poll', guard_source)
        self.assertNotIn('name="poll_interval_seconds"', guard_source)
        self.assertLess(guard_source.index('data-transcode-guard-active'), guard_source.index('data-transcode-guard-violations'))
        self.assertNotIn('Ambito globale', guard_source)
        self.assertNotIn('transcode-guard-global-grid', guard_source)
        self.assertIn('transcode-guard-rules-shell', guard_source)
        self.assertIn('data-transcode-guard-rule-list', guard_source)
        self.assertIn('data-transcode-guard-rule-editor', guard_source)
        self.assertIn('data-transcode-guard-rule-enabled-switch', guard_source)
        self.assertIn('data-transcode-guard-editor-body', guard_source)
        self.assertLess(guard_source.index('Dettaglio regola'), guard_source.index('data-transcode-guard-rule-enabled-switch'))
        self.assertLess(guard_source.index('data-transcode-guard-rule-enabled-switch'), guard_source.index('data-transcode-guard-editor-body'))
        self.assertLess(guard_source.index('data-rule-field="enabled"'), guard_source.index('data-transcode-guard-editor-body'))
        self.assertNotIn('transcode-guard-inline-check', guard_source)
        self.assertIn('class="transcode-guard-rule-name-field transcode-guard-field-wide"', guard_source)
        self.assertIn('data-action="transcode-guard-rule-add"', guard_source)
        self.assertNotIn('data-action="transcode-guard-group-add"', guard_source)
        self.assertNotIn('data-rule-field="type"', guard_source)
        self.assertNotIn('data-rule-field="profile"', guard_source)
        self.assertIn('data-rule-field="video_state"', guard_source)
        self.assertIn('data-rule-field="audio_state"', guard_source)
        self.assertIn('data-rule-field="remux_state"', guard_source)
        self.assertIn('Qualsiasi</option>', guard_source)
        self.assertIn('Transcodifica</option>', guard_source)
        self.assertIn('Diretto</option>', guard_source)
        self.assertIn('Presente</option>', guard_source)
        self.assertIn('Assente</option>', guard_source)
        self.assertIn('Nessuna soglia', guard_source)
        self.assertIn('576p+', guard_source)
        self.assertIn('480p+', guard_source)
        self.assertIn('data-rule-field="mode"', guard_source)
        self.assertIn('transcode-guard-editor-row-three', guard_source)
        self.assertIn('data-rule-field="ignore_paused"', guard_source)
        self.assertIn('Pausa riproduzione', guard_source)
        self.assertIn('Soglia qualità', guard_source)
        self.assertIn('qualità sorgente', guard_source)
        self.assertIn('regola può intervenire', guard_source)
        self.assertIn('Considera: valuta anche le riproduzioni in pausa. Ignora: non considera le sessioni in pausa.', guard_source)
        self.assertNotIn('più richieste', guard_source)
        self.assertIn('Controlla qualità di riproduzione', operations_source)
        self.assertIn('evitare perdita di qualità', operations_source)
        self.assertIn('Sposta giù', operations_source)
        self.assertNotIn('Soglia qualita', guard_source)
        self.assertNotIn('qualita', guard_source)
        self.assertNotIn('qualita', operations_source)
        self.assertIn('<option value="false">Considera</option>', guard_source)
        self.assertIn('<option value="true">Ignora</option>', guard_source)
        self.assertNotIn('<input type="checkbox" data-rule-field="ignore_paused"', guard_source)
        self.assertLess(guard_source.index('data-rule-field="mode"'), guard_source.index('data-rule-field="min_source_height"'))
        self.assertLess(guard_source.index('data-rule-field="min_source_height"'), guard_source.index('data-rule-field="ignore_paused"'))
        self.assertLess(guard_source.index('data-rule-field="ignore_paused"'), guard_source.index('transcode-guard-message-options'))
        self.assertNotIn('value="warn_then_pause"', guard_source)
        self.assertNotIn('value="pause"', guard_source)
        self.assertNotIn('Metti in pausa', guard_source)
        self.assertNotIn('warn_then_pause', operations_source)
        self.assertIn('transcode-guard-message-grid', guard_source)
        self.assertNotIn('transcode-guard-global-section', guard_source)
        self.assertNotIn('transcode-guard-server-section', guard_source)
        self.assertIn('data-transcode-guard-rule-server-list', guard_source)
        self.assertIn('data-rule-field="server_ids"', guard_source)
        self.assertIn('Server interessati', guard_source)
        self.assertIn('transcode-guard-rule-server-title', guard_source)
        self.assertIn('<h4 title="Seleziona i server su cui questa regola può intervenire. Serve almeno un server per attivarla.">Server interessati</h4>', guard_source)
        self.assertEqual(guard_source.count('transcode-guard-rule-divider'), 6)
        self.assertLess(guard_source.index('transcode-guard-rule-divider'), guard_source.index('class="transcode-guard-rule-name-field'))
        self.assertLess(guard_source.index('class="transcode-guard-rule-name-field'), guard_source.index('transcode-guard-rule-server-block'))
        self.assertLess(guard_source.index('class="transcode-guard-rule-divider transcode-guard-field-wide"'), guard_source.index('class="transcode-guard-message-title-field'))
        self.assertIn('Serve almeno un server per attivarla', guard_source)
        self.assertNotIn('Vuoto significa tutti i server abilitati', guard_source)
        self.assertNotIn('data-transcode-guard-preset', guard_source)
        self.assertNotIn('Monitoraggio</button>', guard_source)
        self.assertNotIn('Morbido</button>', guard_source)
        self.assertNotIn('Rigido</button>', guard_source)
        self.assertNotIn('data-transcode-guard-status', guard_source)
        self.assertNotIn('name="warning_timeout_ms"', guard_source)
        self.assertIn('data-rule-field="message_display_mode"', guard_source)
        self.assertIn('Temporaneo</option>', guard_source)
        self.assertNotIn('Toast temporaneo', guard_source)
        self.assertIn('Conferma richiesta', guard_source)
        self.assertIn('scegli tra popup breve e conferma da chiudere', guard_source)
        self.assertNotIn('Durata messaggio', guard_source)
        self.assertNotIn('transcode-guard-help', guard_source)
        self.assertNotIn('fa-circle-info', guard_source)
        self.assertIn('title="Avvia o ferma il monitor automatico di Transcode Guard.', guard_source)
        self.assertIn('title="Azione da eseguire quando la regola corrisponde.', guard_source)
        self.assertIn('title="Seleziona i server su cui questa regola', guard_source)
        self.assertIn('transcode-guard-section-heading', guard_source)
        self.assertNotIn('transcode-guard-actions-panel', guard_source)
        self.assertIn('transcode-guard-rule-save-row', guard_source)
        self.assertIn('Salva modifiche', guard_source)
        self.assertNotIn('Salva impostazioni', guard_source)
        self.assertNotIn('data-action="transcode-guard-check"', guard_source)
        self.assertNotIn('Verifica ora', guard_source)
        self.assertLess(guard_source.index('Esclusioni della regola'), guard_source.index('transcode-guard-rule-save-row'))
        self.assertIn('Opzioni messaggio', guard_source)
        self.assertIn('transcode-guard-message-options', guard_source)
        self.assertIn('transcode-guard-timing-grid', guard_source)
        self.assertLess(guard_source.index('Opzioni messaggio'), guard_source.index('transcode-guard-timing-grid'))
        self.assertNotIn('data-rule-field="grace_seconds"', guard_source)
        self.assertNotIn('>Attesa</span>', guard_source)
        self.assertLess(guard_source.index('data-rule-field="message_display_mode"'), guard_source.index('transcode-guard-message-grid'))
        self.assertIn('rows="4"', guard_source)
        self.assertIn('class="transcode-guard-stop-delay-field"', guard_source)
        self.assertIn('>Ferma</span>', guard_source)
        self.assertNotIn('>Correzione</span>', guard_source)
        self.assertIn('data-rule-field="max_warnings"', guard_source)
        self.assertIn('Apparizioni', guard_source)
        self.assertIn('Numero massimo di apparizioni del messaggio per la stessa violazione.', guard_source)
        self.assertNotIn('>Avvisi</span>', guard_source)
        self.assertIn('data-rule-field="message_cooldown_seconds"', guard_source)
        self.assertIn('data-rule-field="message_header"', guard_source)
        self.assertIn('class="transcode-guard-message-title-field transcode-guard-field-wide"', guard_source)
        self.assertNotIn('name="excluded_users"', guard_source)
        self.assertNotIn('name="excluded_devices"', guard_source)
        self.assertNotIn('name="excluded_ips"', guard_source)
        self.assertIn('data-rule-field="excluded_users"', guard_source)
        self.assertIn('data-rule-field="excluded_clients"', guard_source)
        self.assertIn('data-rule-field="excluded_devices"', guard_source)
        self.assertIn('data-rule-field="excluded_ips"', guard_source)
        self.assertIn('<details class="transcode-guard-rule-exclusions-flow">', guard_source)
        self.assertIn('<summary class="transcode-guard-rule-exclusions-summary">', guard_source)
        self.assertIn('transcode-guard-rule-exclusions-toggle', guard_source)
        self.assertIn('fa-chevron-down', guard_source)
        self.assertNotIn('class="transcode-guard-advanced-details transcode-guard-rule-exclusions"', guard_source)
        self.assertNotIn('<details class="transcode-guard-rule-exclusions-flow" open>', guard_source)
        self.assertLess(guard_source.index('transcode-guard-message-grid'), guard_source.index('Esclusioni della regola'))
        self.assertIn('data-transcode-guard-active', guard_source)
        self.assertIn('data-transcode-guard-events', guard_source)
        self.assertIn('Interventi recenti', guard_source)
        self.assertIn('data-transcode-guard-clear-before-date', guard_source)
        self.assertIn('data-action="transcode-guard-clear-before"', guard_source)
        self.assertIn('data-action="transcode-guard-clear-all"', guard_source)
        self.assertIn('Registro stream', guard_source)
        self.assertIn('data-transcode-guard-streams', guard_source)
        self.assertIn('data-transcode-guard-hide-correct', guard_source)
        self.assertIn('Nascondi corrette', guard_source)
        self.assertIn('data-transcode-guard-retention-days', guard_source)
        self.assertIn('stream_history_retention_days', guard_source)
        self.assertIn('data-transcode-guard-stream-clear-before-date', guard_source)
        self.assertIn('data-action="transcode-guard-stream-clear-before"', guard_source)
        self.assertIn('data-action="transcode-guard-stream-clear-all"', guard_source)
        self.assertNotIn('data-transcode-guard-summary', guard_source)
        self.assertIn("/api/emby/transcode-guard/settings", operations_source)
        self.assertNotIn("/api/emby/transcode-guard/check-now", operations_source)
        self.assertIn("/api/emby/transcode-guard/events/cleanup", operations_source)
        self.assertIn("/api/emby/transcode-guard/streams/cleanup", operations_source)
        self.assertNotIn("applyTranscodeGuardPreset", operations_source)
        self.assertIn("startTranscodeGuardStatusPolling", operations_source)
        self.assertIn("transcodeGuardPollTimer", operations_source)
        self.assertIn("refreshTranscodeGuardRuntimeStatus({ syncForm: false })", operations_source)
        self.assertIn("refreshTranscodeGuardRuntimeStatus({ syncForm: true })", operations_source)
        self.assertIn("autoSaveTranscodeGuardSettings", operations_source)
        self.assertIn("Regole stream salvate.", operations_source)
        self.assertIn("Modifiche regola salvate.", operations_source)
        self.assertIn("transcodeGuardEnabledInput", operations_source)
        self.assertNotIn("transcodeGuardPollInput", operations_source)
        self.assertIn("transcodeGuardDefaultPollSeconds", operations_source)
        self.assertIn("messageMode === 'toast'", operations_source)
        self.assertIn("transcode-guard-field-disabled", operations_source)
        self.assertIn('<option value="confirmation">Conferma richiesta</option>', guard_source)
        self.assertIn("let transcodeGuardRules = [];", operations_source)
        self.assertIn("enabled: false,", operations_source)
        self.assertIn("enabled: rule.enabled !== false && serverIds.length > 0", operations_source)
        self.assertIn("normalizeTranscodeGuardRuleClient", operations_source)
        self.assertIn("renderTranscodeGuardRules", operations_source)
        self.assertIn("fillTranscodeGuardRuleEditor", operations_source)
        self.assertIn("transcodeGuardRuleEnabledSwitch", operations_source)
        self.assertIn("transcodeGuardRuleEnabledSwitch.hidden = !rule", operations_source)
        self.assertIn("rules: transcodeGuardRules.map", operations_source)
        self.assertIn("Seleziona almeno un server", operations_source)
        self.assertIn("canEnableTranscodeGuardRule", operations_source)
        self.assertIn("server_ids: normalizeTranscodeGuardList", operations_source)
        self.assertNotIn("server_ids: normalizeTranscodeGuardList(child.server_ids).length ? child.server_ids : rule.server_ids", operations_source)
        self.assertNotIn("excluded_users: normalizeTranscodeGuardList(child.excluded_users).length ? child.excluded_users : rule.excluded_users", operations_source)
        self.assertNotIn("excluded_clients: normalizeTranscodeGuardList(child.excluded_clients).length ? child.excluded_clients : rule.excluded_clients", operations_source)
        self.assertNotIn("excluded_devices: normalizeTranscodeGuardList(child.excluded_devices).length ? child.excluded_devices : rule.excluded_devices", operations_source)
        self.assertNotIn("excluded_ips: normalizeTranscodeGuardList(child.excluded_ips).length ? child.excluded_ips : rule.excluded_ips", operations_source)
        self.assertNotIn("data-action=\"transcode-guard-rule-child-add\"", operations_source)
        self.assertNotIn("transcode-guard-rule-child-add", operations_source)
        self.assertIn("moveTranscodeGuardRule", operations_source)
        self.assertIn("duplicateTranscodeGuardRule", operations_source)
        self.assertIn("message_cooldown_seconds: Number", operations_source)
        self.assertIn("max_warnings: Number", operations_source)
        self.assertIn("const transcodeGuardMessageFieldNames = new Set", operations_source)
        self.assertIn("syncTranscodeGuardMessageFieldsAvailability", operations_source)
        self.assertIn("mode === 'monitor' || mode === 'stop'", operations_source)
        self.assertIn("const stopDelayDisabled = mode !== 'warn_then_stop';", operations_source)
        self.assertIn("stopDelayLabel.classList.toggle('transcode-guard-field-disabled', stopDelayDisabled)", operations_source)
        self.assertNotIn("stopDelayLabel.hidden = stopDelayHidden", operations_source)
        self.assertIn("renderTranscodeGuardEvents", operations_source)
        self.assertIn("recent_events", operations_source)
        self.assertIn("stream_history", operations_source)
        self.assertIn("playback_events", operations_source)
        self.assertIn("data-transcode-guard-playback-events", guard_source)
        self.assertIn("renderTranscodeGuardPlaybackEvents", operations_source)
        self.assertIn("renderTranscodeGuardEventTags", operations_source)
        self.assertNotIn("transcodeGuardCompactedEventActions", operations_source)
        self.assertNotIn("actions.length <= 5", operations_source)
        self.assertIn("renderTranscodeGuardStreamHistory", operations_source)
        self.assertIn("action_label", operations_source)
        self.assertIn("transcodeGuardActionLabel", operations_source)
        self.assertIn("renderTranscodeGuardBadge(entry.transcode_guard)", operations_source)
        self.assertIn(".transcode-guard-card", css_source)
        self.assertIn(".transcode-guard-header", css_source)
        self.assertIn(".transcode-guard-title-block", css_source)
        self.assertIn(".transcode-guard-header-switch", css_source)
        card_css = css_source[
            css_source.index(".transcode-guard-card") : css_source.index(".transcode-guard-section-title")
        ]
        self.assertIn("grid-template-columns: minmax(0, 1fr);", card_css)
        shared_header_css = css_source[css_source.index(".page-card-header") : css_source.index(".page-card-actions")]
        self.assertIn("display: flex;", shared_header_css)
        self.assertIn("justify-content: space-between;", shared_header_css)
        self.assertIn("align-items: flex-start;", shared_header_css)
        self.assertIn("flex-wrap: wrap;", shared_header_css)
        shared_actions_css = css_source[
            css_source.index(".page-card-actions") : css_source.index(".latest-header")
        ]
        self.assertIn("margin-left: auto;", shared_actions_css)
        self.assertIn("justify-content: flex-end;", shared_actions_css)
        header_css = css_source[
            css_source.index(".transcode-guard-header {") : css_source.index(".transcode-guard-title-block")
        ]
        self.assertIn("padding-bottom: 0.85rem;", header_css)
        self.assertIn("border-bottom: 1px solid #e5eaf2;", header_css)
        self.assertNotIn("padding-right:", header_css)
        self.assertNotIn(".transcode-guard-header h2", css_source)
        self.assertNotIn(".transcode-guard-header .tagline", css_source)
        title_block_css = css_source[
            css_source.index(".transcode-guard-title-block") : css_source.index(".transcode-guard-header-actions")
        ]
        self.assertIn("max-width: min(100%, 58rem);", title_block_css)
        transcode_header_css = css_source[
            css_source.index(".transcode-guard-header {") : css_source.index(".transcode-guard-title-block")
        ]
        self.assertNotIn("position: absolute;", transcode_header_css)
        self.assertNotIn("right: 0;", transcode_header_css)
        section_css = css_source[
            css_source.index(".transcode-guard-section {") : css_source.index(".transcode-guard-policy-card")
        ]
        self.assertIn("border: 1px solid #e1e6f0;", section_css)
        self.assertIn("border-radius: 8px;", section_css)
        self.assertIn("background: #fff;", section_css)
        header_switch_css = css_source[
            css_source.index(".transcode-guard-header-switch") : css_source.index(".transcode-guard-state-grid")
        ]
        self.assertIn("border: 0;", header_switch_css)
        switch_css = css_source[
            css_source.index(".transcode-guard-switch {") : css_source.index(".transcode-guard-switch .transcode-guard-label-text")
        ]
        self.assertIn("flex-direction: row;", switch_css)
        self.assertIn(".transcode-guard-form label.transcode-guard-switch", css_source)
        self.assertIn("width: 2rem;", css_source)
        self.assertIn("height: 1.05rem;", css_source)
        self.assertIn(".transcode-guard-state-grid", css_source)
        self.assertNotIn(".transcode-guard-hero", css_source)
        self.assertIn(".transcode-guard-metric-card", css_source)
        self.assertNotIn(".transcode-guard-state-poll", css_source)
        self.assertNotIn(".transcode-guard-global-grid", css_source)
        self.assertIn(".transcode-guard-rules-shell", css_source)
        self.assertIn(".transcode-guard-rule-list", css_source)
        self.assertIn(".transcode-guard-rule-row", css_source)
        self.assertIn(".transcode-guard-rule-editor", css_source)
        self.assertIn(".transcode-guard-rule-enabled-switch", css_source)
        self.assertIn(".transcode-guard-rule-enabled-switch[hidden]", css_source)
        self.assertIn(".transcode-guard-rule-server-title", css_source)
        self.assertIn(".transcode-guard-rule-name-field", css_source)
        self.assertIn(".transcode-guard-editor-row", css_source)
        self.assertIn(".transcode-guard-editor-row-three", css_source)
        editor_body_css = css_source[
            css_source.index(".transcode-guard-editor-body") : css_source.index(".transcode-guard-editor-row")
        ]
        self.assertIn("gap: 0.75rem;", editor_body_css)
        editor_row_css = css_source[
            css_source.index(".transcode-guard-editor-row {") : css_source.index(".transcode-guard-editor-row-three")
        ]
        self.assertIn("gap: 0.65rem;", editor_row_css)
        criteria_css = css_source[
            css_source.index(".transcode-guard-criteria-grid") : css_source.index(".transcode-guard-field-grow")
        ]
        self.assertIn("gap: 0.65rem;", criteria_css)
        self.assertIn("grid-template-columns: repeat(3, minmax(0, 1fr));", criteria_css)
        editor_row_three_css = css_source[
            css_source.index(".transcode-guard-editor-row-three") : css_source.index(".transcode-guard-criteria-grid")
        ]
        self.assertIn("grid-template-columns: repeat(3, minmax(0, 1fr));", editor_row_three_css)
        self.assertIn(".transcode-guard-message-grid", css_source)
        self.assertIn(".transcode-guard-message-options", css_source)
        self.assertIn(".transcode-guard-message-settings-disabled", css_source)
        self.assertNotIn(".transcode-guard-actions-panel", css_source)
        self.assertIn(".transcode-guard-rule-save-row", css_source)
        self.assertIn(".transcode-guard-section-heading", css_source)
        self.assertIn(".transcode-guard-timing-grid", css_source)
        self.assertIn(".transcode-guard-events", css_source)
        self.assertIn(".transcode-guard-stream-list", css_source)
        self.assertIn(".transcode-guard-event-actions", css_source)
        self.assertIn(".transcode-guard-stream-tag", css_source)
        self.assertIn(".transcode-guard-event-list", css_source)
        self.assertIn(".transcode-guard-event-tools", css_source)
        self.assertIn(".transcode-guard-event-heading", css_source)
        self.assertIn(".transcode-guard-event-time", css_source)
        self.assertIn(".transcode-guard-event-action.exit", css_source)
        self.assertNotIn(".transcode-guard-advanced-details", css_source)
        self.assertIn(".transcode-guard-rule-exclusions-flow", css_source)
        self.assertIn(".transcode-guard-rule-exclusions-summary", css_source)
        self.assertIn(".transcode-guard-rule-exclusions-toggle", css_source)
        self.assertIn(".transcode-guard-rule-exclusions-flow[open] .transcode-guard-rule-exclusions-toggle", css_source)
        self.assertIn(".transcode-guard-message-title-field", css_source)
        self.assertIn(".transcode-guard-field-disabled", css_source)
        self.assertIn(".transcode-guard-field-disabled .transcode-guard-label-text", css_source)
        self.assertIn("opacity: 0.58;", css_source[css_source.index(".transcode-guard-field-disabled") :])
        divider_css = css_source[
            css_source.index(".transcode-guard-rule-divider") : css_source.index(".transcode-guard-form .transcode-guard-inline-check")
        ]
        self.assertIn("border-top: 1px solid #e5eaf2;", divider_css)
        self.assertIn("margin: 0.1rem 0;", divider_css)
        self.assertNotIn(".transcode-guard-check-list label", css_source)
        server_option_css = css_source[
            css_source.index(".transcode-guard-form .transcode-guard-server-option") : css_source.index(".transcode-guard-exclusions-grid")
        ]
        self.assertIn("display: inline-grid;", server_option_css)
        self.assertIn("grid-template-columns: auto minmax(0, max-content);", server_option_css)
        self.assertIn(".transcode-guard-server-option > input", server_option_css)
        self.assertIn("grid-column: 1;", server_option_css)
        self.assertIn(".transcode-guard-server-option .server-label", server_option_css)
        self.assertIn("grid-column: 2;", server_option_css)
        self.assertNotIn(".transcode-guard-help", css_source)
        self.assertIn("height: var(--transcode-guard-field-height);", css_source)
        self.assertIn("box-sizing: border-box;", css_source)
        self.assertIn("padding: 0 0.52rem;", css_source)
        self.assertIn("grid-template-columns: minmax(13rem, 15rem) repeat(3, minmax(4.5rem, 5.5rem));", css_source)
        self.assertIn(".transcode-guard-rule-divider + .transcode-guard-message-options", css_source)
        self.assertIn("gap: 0.6rem;", css_source)
        self.assertIn("gap: 0.62rem;", css_source)
        self.assertIn("min-height: 6.5rem;", css_source)
        guard_css = css_source[
            css_source.index(".transcode-guard-card") : css_source.index(".stream-badge.guard-danger")
        ]
        self.assertNotIn("cursor: help", guard_css)
        self.assertIn(".stream-badge.guard-danger", css_source)

    def test_operations_tab_exposes_user_stream_stats_tab(self):
        dashboard_source = pathlib.Path("templates/emby_dashboard.html").read_text(encoding="utf-8")
        stats_source = pathlib.Path("templates/partials/emby_transcode_stats.html").read_text(encoding="utf-8")
        operations_source = pathlib.Path("static/emby_operations.js").read_text(encoding="utf-8")
        css_source = pathlib.Path("static/emby.css").read_text(encoding="utf-8")

        self.assertIn('data-tab="transcode-stats"', dashboard_source)
        self.assertIn('Stats utenti', dashboard_source)
        self.assertIn('{% include "partials/emby_transcode_stats.html" %}', dashboard_source)
        self.assertIn('data-tab-panel="transcode-stats"', stats_source)
        self.assertIn('data-transcode-stats-panel', stats_source)
        self.assertIn('Statistiche stream utenti', stats_source)
        self.assertIn('data-transcode-stats-period', stats_source)
        self.assertIn('data-transcode-stats-server', stats_source)
        self.assertIn('data-transcode-stats-user', stats_source)
        self.assertIn('data-transcode-stats-client', stats_source)
        self.assertIn('data-transcode-stats-issues-only', stats_source)
        self.assertIn('data-transcode-stats-summary', stats_source)
        self.assertIn('data-transcode-stats-users', stats_source)
        self.assertIn('data-transcode-stats-history', stats_source)
        self.assertIn('Nascondi corrette', stats_source)
        self.assertIn('/api/emby/transcode-guard/stats', operations_source)
        self.assertIn('renderTranscodeUserStats', operations_source)
        self.assertIn('loadTranscodeUserStats', operations_source)
        self.assertIn('transcode-stats-user-table', css_source)
        self.assertIn('transcode-stats-trend-dot', css_source)

    def test_transcode_guard_assets_have_current_cache_busters(self):
        dashboard_source = pathlib.Path("templates/emby_dashboard.html").read_text(encoding="utf-8")

        self.assertIn("emby.css') }}?v=20260809-users-multiselect-84", dashboard_source)
        self.assertIn("emby_operations.js') }}?v=20260722-transcode-guard-message-ui", dashboard_source)


if __name__ == "__main__":
    unittest.main()
