import os
import inspect
from pathlib import Path


def test_save_runtime_secret_preserves_existing_env_file_values(tmp_path, monkeypatch):
    from services.runtime_env import save_runtime_secret

    config_file = tmp_path / "config.json"
    env_file = tmp_path / ".env"
    env_file.write_text(
        "# OctoHubs Environment Variables\n"
        "OCTOHUBS_DB_PASSWORD=supersecret\n"
        "WEBHOOK_SECRET=old-secret\n",
        encoding="utf-8",
    )
    monkeypatch.setenv("OCTOHUBS_CONFIG_FILE", str(config_file))
    monkeypatch.delenv("WEBHOOK_SECRET", raising=False)

    saved_path = save_runtime_secret("WEBHOOK_SECRET", "bridge-secret")

    assert saved_path == env_file
    assert os.environ["WEBHOOK_SECRET"] == "bridge-secret"
    assert env_file.read_text(encoding="utf-8") == (
        "# OctoHubs Environment Variables\n"
        "# Generated by OctoHubs configuration\n\n"
        "OCTOHUBS_DB_PASSWORD=supersecret\n"
        "WEBHOOK_SECRET=bridge-secret\n"
    )


def test_load_runtime_env_file_applies_webhook_secret_when_current_value_is_empty(tmp_path, monkeypatch):
    from services.runtime_env import load_runtime_env_file

    config_file = tmp_path / "config.json"
    (tmp_path / ".env").write_text("WEBHOOK_SECRET=bridge-secret\n", encoding="utf-8")
    monkeypatch.setenv("OCTOHUBS_CONFIG_FILE", str(config_file))
    monkeypatch.setenv("WEBHOOK_SECRET", "")

    loaded = load_runtime_env_file()

    assert loaded == tmp_path / ".env"
    assert os.environ["WEBHOOK_SECRET"] == "bridge-secret"


def test_load_runtime_env_file_does_not_override_existing_non_empty_webhook_secret(tmp_path, monkeypatch):
    from services.runtime_env import load_runtime_env_file

    config_file = tmp_path / "config.json"
    (tmp_path / ".env").write_text("WEBHOOK_SECRET=file-secret\n", encoding="utf-8")
    monkeypatch.setenv("OCTOHUBS_CONFIG_FILE", str(config_file))
    monkeypatch.setenv("WEBHOOK_SECRET", "env-secret")

    load_runtime_env_file()

    assert os.environ["WEBHOOK_SECRET"] == "env-secret"


def test_runtime_env_file_path_defaults_next_to_local_config(tmp_path, monkeypatch):
    from services.runtime_env import runtime_env_file_path

    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv("OCTOHUBS_CONFIG_FILE", raising=False)
    monkeypatch.delenv("OCTOHUB_CONFIG_FILE", raising=False)

    assert runtime_env_file_path() == tmp_path / ".env"


def test_runtime_env_file_path_accepts_legacy_octohub_config_env(tmp_path, monkeypatch):
    from services.runtime_env import runtime_env_file_path

    config_file = tmp_path / "legacy" / "config.json"
    monkeypatch.delenv("OCTOHUBS_CONFIG_FILE", raising=False)
    monkeypatch.setenv("OCTOHUB_CONFIG_FILE", str(config_file))

    assert runtime_env_file_path() == config_file.parent / ".env"


def test_runtime_secret_configured_reads_runtime_env_file(tmp_path, monkeypatch):
    from services.runtime_env import runtime_secret_configured

    config_file = tmp_path / "config.json"
    (tmp_path / ".env").write_text("WEBHOOK_SECRET=bridge-secret\n", encoding="utf-8")
    monkeypatch.setenv("OCTOHUBS_CONFIG_FILE", str(config_file))
    monkeypatch.setenv("WEBHOOK_SECRET", "")

    assert runtime_secret_configured("WEBHOOK_SECRET") is True


def test_configuration_route_accepts_webhook_secret_without_config_payload_storage():
    from services.routes import update_config_route

    signature = inspect.signature(update_config_route)
    route_source = inspect.getsource(update_config_route)

    assert "webhook_secret" in signature.parameters
    assert "save_runtime_secret" in route_source
    assert 'app_settings["WEBHOOK_SECRET"]' not in route_source


def test_configuration_template_exposes_event_bridge_secret_field():
    template = Path("templates/configuration.html").read_text(encoding="utf-8")

    assert "Event Bridge Emby" in template
    assert 'name="webhook_secret"' in template
    assert "webhook_secret_configured" in template
    assert 'data-tab="event-bridge"' in template
    assert 'data-tab-panel="event-bridge"' in template
    assert 'data-event-bridge-live="/configuration/event-bridge/status"' in template
    assert "event_bridge_diagnostics.js" in template
    assert 'action="/configuration/event-bridge"' in template
    assert 'value=""' in template
