"""API client helpers for Emby user management."""

from emby_users.api_client_items import (
    _fetch_emby_user_last_playback,
    _fetch_emby_user_items_for_sync,
    _fetch_emby_user_favorite_items,
    _fetch_emby_user_media_items,
    _fetch_emby_items_by_provider_ids,
    _fetch_emby_items_by_safe_fallback,
    _mark_emby_item_played,
    _mark_emby_item_unplayed,
    _set_emby_item_resume,
    _set_emby_item_hide_from_resume,
    _set_emby_item_favorite,
    _fetch_emby_user_playlists,
    _fetch_emby_playlist_items,
    _create_emby_playlist,
    _add_emby_playlist_items,
    _remove_emby_playlist_entries,
    _delete_emby_playlist,
)
from emby_users.api_client_users import (
    _fetch_emby_users_list,
    _fetch_emby_user_details,
    _update_emby_user_policy,
    _update_emby_user_configuration,
    _fetch_emby_user_display_preferences,
    _update_emby_user_display_preferences,
    _fetch_emby_features,
    _rename_emby_user,
    _update_emby_user_password,
    _create_emby_user,
    _delete_emby_user,
)

__all__ = [
    "_fetch_emby_users_list",
    "_fetch_emby_user_details",
    "_update_emby_user_policy",
    "_update_emby_user_configuration",
    "_fetch_emby_user_display_preferences",
    "_update_emby_user_display_preferences",
    "_fetch_emby_features",
    "_rename_emby_user",
    "_update_emby_user_password",
    "_fetch_emby_user_last_playback",
    "_fetch_emby_user_items_for_sync",
    "_fetch_emby_user_favorite_items",
    "_fetch_emby_user_media_items",
    "_fetch_emby_items_by_provider_ids",
    "_fetch_emby_items_by_safe_fallback",
    "_mark_emby_item_played",
    "_mark_emby_item_unplayed",
    "_set_emby_item_resume",
    "_set_emby_item_hide_from_resume",
    "_set_emby_item_favorite",
    "_fetch_emby_user_playlists",
    "_fetch_emby_playlist_items",
    "_create_emby_playlist",
    "_add_emby_playlist_items",
    "_remove_emby_playlist_entries",
    "_delete_emby_playlist",
    "_create_emby_user",
    "_delete_emby_user",
]
