export type LatestTemplateToken = {
  token: string;
  label: string;
  example: string;
  description: string;
  group: string;
};

export const latestTemplateTokens: LatestTemplateToken[] = [
  { token: "{title}", label: "Titolo", example: "Dune - Parte Due", description: "Titolo principale.", group: "Identità" },
  { token: "{original_title}", label: "Titolo originale", example: "Dune: Part Two", description: "Titolo originale, se disponibile.", group: "Identità" },
  { token: "{year}", label: "Anno", example: "2024", description: "Anno di uscita o produzione.", group: "Identità" },
  { token: "{type}", label: "Tipo", example: "movie", description: "movie, series oppure episode.", group: "Identità" },
  { token: "{server}", label: "Server", example: "Green", description: "Nome del server Emby.", group: "Identità" },
  { token: "{library}", label: "Libreria", example: "Cinema 4K", description: "Nome della libreria Emby.", group: "Identità" },
  { token: "{library_name}", label: "Libreria (alias)", example: "Cinema 4K", description: "Alias di {library}.", group: "Identità" },

  { token: "{series_name}", label: "Nome serie", example: "Stranger Things", description: "Nome della serie per gli episodi.", group: "Serie ed episodi" },
  { token: "{season_number}", label: "Numero stagione", example: "5", description: "Numero della stagione.", group: "Serie ed episodi" },
  { token: "{season_name}", label: "Nome stagione", example: "Stagione 5", description: "Nome della stagione, se disponibile.", group: "Serie ed episodi" },
  { token: "{episode_number}", label: "Numero episodio", example: "8", description: "Numero dell'episodio.", group: "Serie ed episodi" },
  { token: "{episode_title}", label: "Titolo episodio", example: "La porta", description: "Titolo dell'episodio.", group: "Serie ed episodi" },
  { token: "{episode_count}", label: "Numero episodi", example: "42", description: "Episodi presenti.", group: "Serie ed episodi" },
  { token: "{season_count}", label: "Numero stagioni", example: "5", description: "Stagioni presenti.", group: "Serie ed episodi" },
  { token: "{episodes}", label: "Episodi (lista)", example: "S05E05, S05E06", description: "Episodi multipli rilevati.", group: "Serie ed episodi" },
  { token: "{episodes_with_titles}", label: "Episodi e titoli", example: "S05E05 - Il corridoio", description: "Episodi con titolo.", group: "Serie ed episodi" },

  { token: "{quality}", label: "Qualita", example: "2160p", description: "Qualita video.", group: "Versione e qualita" },
  { token: "{video_codec}", label: "Codec video", example: "hevc", description: "Codec video.", group: "Versione e qualita" },
  { token: "{audio_codec}", label: "Codec audio", example: "dts-hd", description: "Codec audio principale.", group: "Versione e qualita" },
  { token: "{audio_channels}", label: "Canali audio", example: "5.1", description: "Layout o numero dei canali audio.", group: "Versione e qualita" },
  { token: "{bitrate}", label: "Bitrate", example: "18.2", description: "Bitrate stimato.", group: "Versione e qualita" },
  { token: "{size}", label: "Dimensione", example: "12.4 GB", description: "Dimensione del file.", group: "Versione e qualita" },
  { token: "{source_name}", label: "Sorgente", example: "Versione 4K", description: "Nome sorgente Emby.", group: "Versione e qualita" },
  { token: "{path}", label: "Percorso", example: "/mnt/media/movies/Dune", description: "Percorso del file.", group: "Versione e qualita" },
  { token: "{resolution}", label: "Risoluzione", example: "3840x2160", description: "Risoluzione video.", group: "Versione e qualita" },
  { token: "{container}", label: "Container", example: "mkv", description: "Container del file.", group: "Versione e qualita" },
  { token: "{video_details}", label: "Dettagli video", example: "HEVC - Dolby Vision", description: "Codec e HDR.", group: "Versione e qualita" },
  { token: "{audio_details}", label: "Audio completo", example: "Italiano Dolby Atmos - Inglese DTS-HD MA 7.1", description: "Tutte le tracce audio con formato.", group: "Versione e qualita" },
  { token: "{audio_ita}", label: "Audio italiano", example: "Italiano Dolby Atmos", description: "Tracce audio italiane.", group: "Versione e qualita" },
  { token: "{audio_eng}", label: "Audio inglese", example: "Inglese DTS-HD MA 7.1", description: "Tracce audio inglesi.", group: "Versione e qualita" },
  { token: "{audio_fra}", label: "Audio francese", example: "Francese Dolby Digital+ 5.1", description: "Tracce audio francesi.", group: "Versione e qualita" },
  { token: "{audio_spa}", label: "Audio spagnolo", example: "Spagnolo Dolby Digital 5.1", description: "Tracce audio spagnole.", group: "Versione e qualita" },
  { token: "{audio_ger}", label: "Audio tedesco", example: "Tedesco DTS 5.1", description: "Tracce audio tedesche.", group: "Versione e qualita" },
  { token: "{audio_jpn}", label: "Audio giapponese", example: "Giapponese AAC 2.0", description: "Tracce audio giapponesi.", group: "Versione e qualita" },
  { token: "{audio_langs}", label: "Lingue audio", example: "ita, eng, spa", description: "Lingue audio ISO 639-2.", group: "Versione e qualita" },
  { token: "{subtitle_langs}", label: "Lingue sottotitoli", example: "ita, eng", description: "Lingue sottotitoli ISO 639-2.", group: "Versione e qualita" },
  { token: "{version_count}", label: "Numero versioni", example: "2", description: "Numero di file o versioni rilevate.", group: "Versione e qualita" },
  { token: "{best_quality}", label: "Qualita migliore", example: "2160p", description: "Qualita della versione migliore.", group: "Versione e qualita" },
  { token: "{best_resolution}", label: "Risoluzione migliore", example: "3840x2160", description: "Risoluzione della versione migliore.", group: "Versione e qualita" },
  { token: "{best_video_codec}", label: "Codec video migliore", example: "hevc", description: "Codec video della versione migliore.", group: "Versione e qualita" },
  { token: "{best_audio_codec}", label: "Codec audio migliore", example: "dts-hd", description: "Codec audio della versione migliore.", group: "Versione e qualita" },
  { token: "{best_audio_channels}", label: "Canali audio migliori", example: "5.1", description: "Canali audio della versione migliore.", group: "Versione e qualita" },
  { token: "{best_bitrate}", label: "Bitrate migliore", example: "18.2", description: "Bitrate della versione migliore.", group: "Versione e qualita" },
  { token: "{best_size}", label: "Dimensione migliore", example: "12.4 GB", description: "Dimensione della versione migliore.", group: "Versione e qualita" },
  { token: "{best_source_name}", label: "Sorgente migliore", example: "Versione 4K", description: "Sorgente della versione migliore.", group: "Versione e qualita" },
  { token: "{best_video_details}", label: "Dettagli video migliori", example: "HEVC - Dolby Vision", description: "Dettagli video della versione migliore.", group: "Versione e qualita" },
  { token: "{best_audio_details}", label: "Audio migliore", example: "Italiano Dolby Atmos - Inglese DTS-HD MA 7.1", description: "Audio completo della versione migliore.", group: "Versione e qualita" },
  { token: "{best_audio_langs}", label: "Lingue audio migliori", example: "ita, eng", description: "Lingue audio della versione migliore.", group: "Versione e qualita" },
  { token: "{best_subtitle_langs}", label: "Lingue sottotitoli migliori", example: "ita, eng", description: "Lingue sottotitoli della versione migliore.", group: "Versione e qualita" },
  { token: "{best_season_number}", label: "Stagione migliore", example: "5", description: "Stagione associata alla versione migliore.", group: "Versione e qualita" },
  { token: "{best_episode_number}", label: "Episodio migliore", example: "8", description: "Episodio associato alla versione migliore.", group: "Versione e qualita" },
  { token: "{best_episode_title}", label: "Titolo episodio migliore", example: "La porta", description: "Titolo episodio della versione migliore.", group: "Versione e qualita" },

  { token: "{update_type}", label: "Tipo tecnico", example: "update", description: "new, update oppure existing.", group: "Stato e novita" },
  { token: "{update_label}", label: "Etichetta aggiornamento", example: "Nuova versione", description: "Etichetta leggibile dell'aggiornamento.", group: "Stato e novita" },
  { token: "{added_at}", label: "Data aggiunta", example: "27.12.'25", description: "Data di pubblicazione Emby.", group: "Stato e novita" },
  { token: "{batch_id}", label: "ID batch", example: "green:movie:202601011030", description: "Identificatore del batch.", group: "Stato e novita" },

  { token: "{overview}", label: "Trama", example: "La lotta per il destino del pianeta...", description: "Descrizione o overview.", group: "Informazioni editoriali" },
  { token: "{genres}", label: "Generi", example: "Sci-Fi - Avventura", description: "Generi principali.", group: "Informazioni editoriali" },
  { token: "{rating}", label: "Rating", example: "8.6", description: "Community rating Emby.", group: "Informazioni editoriali" },
  { token: "{official_rating}", label: "Classificazione", example: "PG-13", description: "Rating ufficiale per eta.", group: "Informazioni editoriali" },
  { token: "{runtime}", label: "Durata", example: "2h 35m", description: "Durata del film.", group: "Informazioni editoriali" },
  { token: "{premiere_date}", label: "Data premiere", example: "24.12.'25", description: "Data di uscita o premiere.", group: "Informazioni editoriali" },
  { token: "{tagline}", label: "Tagline", example: "Il destino ti chiama.", description: "Tagline di film o serie.", group: "Informazioni editoriali" },
  { token: "{studios}", label: "Studios", example: "Legendary - Warner", description: "Studio di produzione.", group: "Informazioni editoriali" },
  { token: "{production}", label: "Produzione", example: "Legendary - Warner", description: "Alias di {studios}.", group: "Informazioni editoriali" },
  { token: "{production_companies}", label: "Produzione (companies)", example: "Legendary - Warner", description: "Alias di {studios}.", group: "Informazioni editoriali" },

  { token: "{cast}", label: "Cast", example: "Timothee Chalamet - Zendaya", description: "Cast principale, massimo cinque persone.", group: "Cast e crew" },
  { token: "{cast_all}", label: "Cast completo", example: "Timothee Chalamet - Zendaya - ...", description: "Tutto il cast disponibile.", group: "Cast e crew" },
  { token: "{cast_3}", label: "Cast (3)", example: "Timothee Chalamet - Zendaya - Austin Butler", description: "Prime N persone; usa anche {cast_2}, {cast_4} e cosi via.", group: "Cast e crew" },
  { token: "{director}", label: "Regia", example: "Denis Villeneuve", description: "Primo regista disponibile.", group: "Cast e crew" },
  { token: "{directors}", label: "Regia (lista)", example: "Denis Villeneuve", description: "Registi disponibili, solo film.", group: "Cast e crew" },
  { token: "{creators}", label: "Creatori", example: "Vince Gilligan - Peter Gould", description: "Creatori della serie TV.", group: "Cast e crew" },

  { token: "{tmdb_rating}", label: "Voto TMDB", example: "8.6", description: "Rating TMDB, richiede API key.", group: "Rating esterni" },
  { token: "{imdb_rating}", label: "Voto IMDb", example: "8.4", description: "Rating IMDb da MDBList o OMDB.", group: "Rating esterni" },
  { token: "{trakt_rating}", label: "Voto Trakt", example: "8.5", description: "Rating Trakt, richiede client ID.", group: "Rating esterni" },
  { token: "{metacritic_rating}", label: "Metacritic", example: "82/100", description: "Rating Metacritic da MDBList o OMDB.", group: "Rating esterni" },

  { token: "{jellyseerr_request_status_label}", label: "Jellyseerr stato", example: "Richiesta", description: "Stato leggibile della richiesta Jellyseerr.", group: "Jellyseerr" },
  { token: "{jellyseerr_request_status}", label: "Jellyseerr stato (raw)", example: "approved", description: "Codice stato Jellyseerr.", group: "Jellyseerr" },
  { token: "{jellyseerr_request_id}", label: "Jellyseerr ID richiesta", example: "123", description: "ID della richiesta Jellyseerr.", group: "Jellyseerr" },
  { token: "{jellyseerr_requested_by}", label: "Jellyseerr richiesto da", example: "Mario Rossi", description: "Utente che ha creato la richiesta.", group: "Jellyseerr" },
  { token: "{jellyseerr_requested}", label: "Jellyseerr richiesto", example: "true", description: "True se e presente una richiesta.", group: "Jellyseerr" },

  { token: "{image_url}", label: "Poster cache DB", example: "/api/v1/emby/image?server_id=...", description: "Poster dalla cache DB di OctoHubs.", group: "Immagini e link" },
  { token: "{poster_url}", label: "Poster Emby", example: "https://emby/Items/.../Images/Primary", description: "Poster dal server Emby.", group: "Immagini e link" },
  { token: "{tmdb_poster_url}", label: "Poster TMDB", example: "https://image.tmdb.org/t/p/w780/abc.jpg", description: "Poster da TMDB.", group: "Immagini e link" },
  { token: "{backdrop_url}", label: "Backdrop Emby", example: "https://emby/Items/.../Images/Backdrop", description: "Backdrop dal server Emby.", group: "Immagini e link" },
  { token: "{tmdb_backdrop_url}", label: "Backdrop TMDB", example: "https://image.tmdb.org/t/p/w1280/abc.jpg", description: "Backdrop da TMDB.", group: "Immagini e link" },
  { token: "{logo_url}", label: "Logo Emby", example: "https://emby/Items/.../Images/Logo", description: "Logo dal server Emby.", group: "Immagini e link" },
  { token: "{tmdb_logo_url}", label: "Logo TMDB", example: "https://image.tmdb.org/t/p/w500/abc.png", description: "Logo da TMDB.", group: "Immagini e link" },
  { token: "{banner_url}", label: "Banner Emby", example: "https://emby/Items/.../Images/Banner", description: "Banner dal server Emby.", group: "Immagini e link" },
  { token: "{tmdb_banner_url}", label: "Banner TMDB", example: "https://image.tmdb.org/t/p/w1280/abc.jpg", description: "Banner da TMDB.", group: "Immagini e link" },
  { token: "{thumb_url}", label: "Thumbnail Emby", example: "https://emby/Items/.../Images/Thumb", description: "Thumbnail dal server Emby.", group: "Immagini e link" },
  { token: "{tmdb_thumb_url}", label: "Thumbnail TMDB", example: "https://image.tmdb.org/t/p/w1280/abc.jpg", description: "Thumbnail da TMDB.", group: "Immagini e link" },
  { token: "{emby_url}", label: "Link Emby", example: "https://emby/web/.../itemdetails.html", description: "Scheda Emby.", group: "Immagini e link" },
  { token: "{tmdb_id}", label: "ID TMDB", example: "123456", description: "ID TMDB, se disponibile.", group: "Immagini e link" },
  { token: "{imdb_id}", label: "ID IMDb", example: "tt1234567", description: "ID IMDb, se disponibile.", group: "Immagini e link" },
  { token: "{tvdb_id}", label: "ID TVDB", example: "98765", description: "ID TVDB, se disponibile.", group: "Immagini e link" },
  { token: "{trakt_id}", label: "ID Trakt", example: "dune-2024", description: "ID Trakt, se disponibile.", group: "Immagini e link" },
  { token: "{tmdb_url}", label: "Link TMDB", example: "https://www.themoviedb.org/movie/123456", description: "Scheda TMDB.", group: "Immagini e link" },
  { token: "{imdb_url}", label: "Link IMDb", example: "https://www.imdb.com/title/tt1234567", description: "Scheda IMDb.", group: "Immagini e link" },
  { token: "{tvdb_url}", label: "Link TVDB", example: "https://thetvdb.com/?id=98765", description: "Scheda TVDB.", group: "Immagini e link" },
  { token: "{trakt_url}", label: "Link Trakt", example: "https://trakt.tv/movies/dune-2024", description: "Scheda Trakt.", group: "Immagini e link" },

  { token: "{% for v in versions %}", label: "Loop versioni (inizio)", example: "{% for v in versions %}", description: "Ciclo Jinja2 sulle versioni; usa v.quality, v.audio_details e simili.", group: "Jinja2 avanzato" },
  { token: "{% endfor %}", label: "Loop versioni (fine)", example: "{% endfor %}", description: "Chiude il ciclo sulle versioni.", group: "Jinja2 avanzato" },
];
