from typing import Any, List

def get_collection(media_type: str, extended: str = ...) -> List[Any]: ...
def search_by_id(id: str, id_type: str = ..., media_type: str = ...) -> List[Any]: ...
def __getattr__(name: str) -> Any: ...
