"""Storage subpackage."""

from .database import DatabaseStorage, is_sqlalchemy_available
from .storage_app_settings import StorageAppSettingsMixin
from .storage_collections import StorageCollectionsMixin
from .storage_core import StorageCoreMixin
from .storage_errors import StorageError
from .storage_image_cache import StorageImageCacheMixin
from .storage_jellyseerr import StorageJellyseerrMixin
from .storage_justwatch import StorageJustWatchMixin
from .storage_latest import StorageLatestMixin
from .storage_maintenance import StorageMaintenanceMixin
from .storage_manual_search import StorageManualSearchMixin
from .storage_probe import StorageProbeMixin
from .storage_requests import StorageRequestsMixin
from .storage_rss import StorageRssMixin
from .storage_users import StorageUsersMixin
from .storage_workflows import StorageWorkflowMixin

from .storage_models import (
    SQLALCHEMY_AVAILABLE,
    SQLAlchemyError,
    Base,
    _utcnow,
    create_engine,
    func,
    or_,
    text,
    sessionmaker,
    AppSettings,
    EmbyLatestCacheMeta,
    EmbyLatestCacheItem,
    JellyseerrRequest,
    EmbyLatestCacheChange,
    EmbyLatestCacheError,
    EmbyImageCache,
    EmbyLatestStateMovie,
    EmbyLatestStateSeries,
    EmbyLatestStateEpisode,
    EmbyLatestStateSeriesGroup,
    EmbyLatestStateSeriesChange,
    EmbyCollectionDefinition,
    EmbyCollectionPoster,
    EmbyCollectionBackdrop,
    RequestRuleEntry,
    ScanResultEntry,
    RequestCacheEntry,
    EmbyLatestProgress,
    LibraryAssociation,
    LibraryGroupOrder,
    TabOrder,
    EmbyProbeBlacklist,
    EmbyProbeQueue,
    EmbyProbeHistory,
    JustWatchCache,
    RssItem,
    CategoryBlacklist,
    CategoryHidden,
    EmbyProbeRecentScan,
    KeyValueEntry,
    EmbyUserLink,
    EmbyUserBackup,
    EmbyIconProfile,
    EmbyIconRule,
    EmbyIconBinding,
    EmbyGroupPassword,
    WorkflowExecution,
    ManualSearchHistory,
    WorkflowStep,
)

from .storage_utils import (
    _parse_datetime_value,
    _normalize_text_array,
    _normalize_int_array,
    _parse_int,
    _normalize_text_value,
    _truncate_text_value,
    _build_connection_url,
)

__all__ = [
    "DatabaseStorage",
    "is_sqlalchemy_available",
    "StorageError",
    "StorageAppSettingsMixin",
    "StorageCollectionsMixin",
    "StorageCoreMixin",
    "StorageImageCacheMixin",
    "StorageJellyseerrMixin",
    "StorageJustWatchMixin",
    "StorageLatestMixin",
    "StorageMaintenanceMixin",
    "StorageManualSearchMixin",
    "StorageProbeMixin",
    "StorageRequestsMixin",
    "StorageRssMixin",
    "StorageUsersMixin",
    "StorageWorkflowMixin",
    "SQLALCHEMY_AVAILABLE",
    "SQLAlchemyError",
    "Base",
    "_utcnow",
    "create_engine",
    "func",
    "or_",
    "text",
    "sessionmaker",
    "AppSettings",
    "EmbyLatestCacheMeta",
    "EmbyLatestCacheItem",
    "JellyseerrRequest",
    "EmbyLatestCacheChange",
    "EmbyLatestCacheError",
    "EmbyImageCache",
    "EmbyLatestStateMovie",
    "EmbyLatestStateSeries",
    "EmbyLatestStateEpisode",
    "EmbyLatestStateSeriesGroup",
    "EmbyLatestStateSeriesChange",
    "EmbyCollectionDefinition",
    "EmbyCollectionPoster",
    "EmbyCollectionBackdrop",
    "RequestRuleEntry",
    "ScanResultEntry",
    "RequestCacheEntry",
    "EmbyLatestProgress",
    "LibraryAssociation",
    "LibraryGroupOrder",
    "TabOrder",
    "EmbyProbeBlacklist",
    "EmbyProbeQueue",
    "EmbyProbeHistory",
    "JustWatchCache",
    "RssItem",
    "CategoryBlacklist",
    "CategoryHidden",
    "EmbyProbeRecentScan",
    "KeyValueEntry",
    "EmbyUserLink",
    "EmbyUserBackup",
    "EmbyIconProfile",
    "EmbyIconRule",
    "EmbyIconBinding",
    "EmbyGroupPassword",
    "WorkflowExecution",
    "ManualSearchHistory",
    "WorkflowStep",
    "_parse_datetime_value",
    "_normalize_text_array",
    "_normalize_int_array",
    "_parse_int",
    "_normalize_text_value",
    "_truncate_text_value",
    "_build_connection_url",
]
