"""Runtime environment helpers for secrets managed from OctoHubs UI."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict

from core.env import octohubs_env


RUNTIME_SECRET_KEYS = {"WEBHOOK_SECRET"}


def runtime_env_file_path() -> Path:
    """Return the .env path next to OCTOHUBS_CONFIG_FILE."""
    config_file = octohubs_env("OCTOHUBS_CONFIG_FILE", "config.json")
    return Path(config_file).expanduser().resolve().parent / ".env"


def load_runtime_env_file() -> Path | None:
    """Load UI-managed runtime secrets from .env without overriding real ENV values."""
    env_file = runtime_env_file_path()
    if not env_file.exists():
        return None
    values = _read_env_file(env_file)
    for key in RUNTIME_SECRET_KEYS:
        value = values.get(key, "").strip()
        current = os.environ.get(key)
        if value and not (isinstance(current, str) and current.strip()):
            os.environ[key] = value
    return env_file


def save_runtime_secret(key: str, value: str) -> Path:
    """Persist a supported runtime secret to .env and apply it immediately."""
    normalized_key = str(key or "").strip().upper()
    if normalized_key not in RUNTIME_SECRET_KEYS:
        raise ValueError(f"Secret runtime non supportato: {key}")
    normalized_value = _normalize_env_value(value)

    env_file = runtime_env_file_path()
    values = _read_env_file(env_file)
    values[normalized_key] = normalized_value
    env_file.parent.mkdir(parents=True, exist_ok=True)
    _write_env_file(env_file, values)
    os.environ[normalized_key] = normalized_value
    return env_file


def runtime_secret_configured(key: str) -> bool:
    """Return whether a runtime secret is currently available."""
    normalized_key = str(key or "").strip().upper()
    if normalized_key not in RUNTIME_SECRET_KEYS:
        return False
    if (os.environ.get(normalized_key) or "").strip():
        return True
    return bool((_read_env_file(runtime_env_file_path()).get(normalized_key) or "").strip())


def _read_env_file(path: Path) -> Dict[str, str]:
    if not path.exists():
        return {}
    values: Dict[str, str] = {}
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return {}
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key:
            values[key] = value.strip()
    return values


def _write_env_file(path: Path, values: Dict[str, str]) -> None:
    lines = [
        "# OctoHubs Environment Variables",
        "# Generated by OctoHubs configuration",
        "",
    ]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _normalize_env_value(value: str) -> str:
    text = str(value or "").strip()
    if "\n" in text or "\r" in text:
        raise ValueError("Il secret runtime non può contenere nuove righe")
    return text
