import {
  Archive,
  Bell,
  Bookmark,
  BookOpen,
  Box,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Camera,
  Captions,
  ChartLine,
  ChartPie,
  Check,
  CirclePlay,
  CircleDot,
  Clapperboard,
  Cloud,
  Code2,
  Copy,
  Cpu,
  Crown,
  Database,
  Disc3,
  Download,
  EthernetPort,
  ExternalLink,
  Eye,
  EyeOff,
  FileArchive,
  FileAudio,
  FileCode2,
  FileImage,
  FileVideo,
  Film,
  Flame,
  Folder,
  FolderOpen,
  Gauge,
  Gamepad2,
  Gem,
  Globe2,
  GraduationCap,
  HardDrive,
  Headphones,
  Heart,
  Hourglass,
  House,
  KeyRound,
  Laptop,
  Layers,
  Link,
  List,
  ListFilter,
  Lock,
  LockOpen,
  Mail,
  MemoryStick,
  MessageCircle,
  Mic,
  Monitor,
  Music2,
  Network,
  Package,
  Pause,
  Pencil,
  Play,
  Plug,
  Power,
  Printer,
  Radio,
  RefreshCw,
  Rocket,
  SatelliteDish,
  Search,
  Send,
  Server,
  Settings2,
  Shield,
  Signal,
  Smartphone,
  Square,
  Star,
  Table2,
  Tablet,
  Tag,
  Terminal,
  Tv,
  Trash2,
  Upload,
  User,
  UsersRound,
  Video,
  Warehouse,
  Wifi,
  Zap,
} from "@/components/ui/icons";
import type { IconComponent } from "@/components/ui/icons";

type IconOption = {
  value: string;
  label: string;
  Icon: IconComponent;
};

const iconOptions: IconOption[] = [
  { value: "fa-server", label: "Server", Icon: Server },
  { value: "fa-tv", label: "TV", Icon: Tv },
  { value: "fa-film", label: "Film", Icon: Film },
  { value: "fa-clapperboard", label: "Ciak", Icon: Clapperboard },
  { value: "fa-circle-play", label: "Riproduci", Icon: CirclePlay },
  { value: "fa-video", label: "Video", Icon: Video },
  { value: "fa-music", label: "Musica", Icon: Music2 },
  { value: "fa-headphones", label: "Cuffie", Icon: Headphones },
  { value: "fa-gamepad", label: "Gamepad", Icon: Gamepad2 },
  { value: "fa-folder", label: "Cartella", Icon: Folder },
  { value: "fa-hard-drive", label: "Disco", Icon: HardDrive },
  { value: "fa-database", label: "Database", Icon: Database },
  { value: "fa-cloud", label: "Cloud", Icon: Cloud },
  { value: "fa-wifi", label: "Wi-Fi", Icon: Wifi },
  { value: "fa-network-wired", label: "Rete", Icon: Network },
  { value: "fa-tower-broadcast", label: "Broadcast", Icon: Radio },
  { value: "fa-desktop", label: "Desktop", Icon: Monitor },
  { value: "fa-globe", label: "Globo", Icon: Globe2 },
  { value: "fa-users", label: "Utenti", Icon: UsersRound },
  { value: "fa-shield", label: "Protezione", Icon: Shield },
  { value: "fa-bell", label: "Notifiche", Icon: Bell },
  { value: "fa-magnifying-glass", label: "Ricerca", Icon: Search },
  { value: "fa-gear", label: "Impostazioni", Icon: Settings2 },
  { value: "fa-box-archive", label: "Archivio", Icon: Archive },
  { value: "fa-play", label: "Play", Icon: Play },
  { value: "fa-pause", label: "Pausa", Icon: Pause },
  { value: "fa-stop", label: "Stop", Icon: Square },
  { value: "fa-compact-disc", label: "Disco", Icon: Disc3 },
  { value: "fa-record-vinyl", label: "Vinile", Icon: CircleDot },
  { value: "fa-camera", label: "Fotocamera", Icon: Camera },
  { value: "fa-microphone", label: "Microfono", Icon: Mic },
  { value: "fa-closed-captioning", label: "Sottotitoli", Icon: Captions },
  { value: "fa-layer-group", label: "Livelli", Icon: Layers },
  { value: "fa-clone", label: "Duplica", Icon: Copy },
  { value: "fa-bars-staggered", label: "Elenco filtrato", Icon: ListFilter },
  { value: "fa-laptop", label: "Laptop", Icon: Laptop },
  { value: "fa-mobile", label: "Mobile", Icon: Smartphone },
  { value: "fa-tablet", label: "Tablet", Icon: Tablet },
  { value: "fa-microchip", label: "CPU", Icon: Cpu },
  { value: "fa-memory", label: "Memoria", Icon: MemoryStick },
  { value: "fa-ethernet", label: "Ethernet", Icon: EthernetPort },
  { value: "fa-satellite-dish", label: "Satellite", Icon: SatelliteDish },
  { value: "fa-signal", label: "Segnale", Icon: Signal },
  { value: "fa-folder-open", label: "Cartella aperta", Icon: FolderOpen },
  { value: "fa-file-video", label: "File video", Icon: FileVideo },
  { value: "fa-file-audio", label: "File audio", Icon: FileAudio },
  { value: "fa-file-image", label: "File immagine", Icon: FileImage },
  { value: "fa-file-code", label: "File codice", Icon: FileCode2 },
  { value: "fa-file-zipper", label: "File archivio", Icon: FileArchive },
  { value: "fa-download", label: "Download", Icon: Download },
  { value: "fa-upload", label: "Upload", Icon: Upload },
  { value: "fa-share", label: "Condividi", Icon: Send },
  { value: "fa-link", label: "Link", Icon: Link },
  { value: "fa-trash", label: "Cestino", Icon: Trash2 },
  { value: "fa-pencil", label: "Modifica", Icon: Pencil },
  { value: "fa-check", label: "Confermato", Icon: Check },
  { value: "fa-ban", label: "Bloccato", Icon: CircleDot },
  { value: "fa-arrows-rotate", label: "Aggiorna", Icon: RefreshCw },
  { value: "fa-arrow-up-right-from-square", label: "Apri esterno", Icon: ExternalLink },
  { value: "fa-star", label: "Stella", Icon: Star },
  { value: "fa-heart", label: "Preferito", Icon: Heart },
  { value: "fa-fire", label: "Popolare", Icon: Flame },
  { value: "fa-bolt", label: "Rapido", Icon: Zap },
  { value: "fa-crown", label: "Leader", Icon: Crown },
  { value: "fa-gem", label: "Gemma", Icon: Gem },
  { value: "fa-bookmark", label: "Segnalibro", Icon: Bookmark },
  { value: "fa-tag", label: "Etichetta", Icon: Tag },
  { value: "fa-clock", label: "Orario", Icon: Hourglass },
  { value: "fa-calendar", label: "Calendario", Icon: CalendarDays },
  { value: "fa-hourglass", label: "Attesa", Icon: Hourglass },
  { value: "fa-lock", label: "Bloccato", Icon: Lock },
  { value: "fa-unlock", label: "Sbloccato", Icon: LockOpen },
  { value: "fa-key", label: "Chiave", Icon: KeyRound },
  { value: "fa-eye", label: "Visibile", Icon: Eye },
  { value: "fa-eye-slash", label: "Nascosto", Icon: EyeOff },
  { value: "fa-user", label: "Utente", Icon: User },
  { value: "fa-user-group", label: "Gruppo utenti", Icon: UsersRound },
  { value: "fa-envelope", label: "Email", Icon: Mail },
  { value: "fa-message", label: "Messaggio", Icon: MessageCircle },
  { value: "fa-paper-plane", label: "Invia", Icon: Send },
  { value: "fa-chart-line", label: "Grafico linea", Icon: ChartLine },
  { value: "fa-chart-pie", label: "Grafico torta", Icon: ChartPie },
  { value: "fa-gauge", label: "Indicatore", Icon: Gauge },
  { value: "fa-list", label: "Elenco", Icon: List },
  { value: "fa-table", label: "Tabella", Icon: Table2 },
  { value: "fa-power-off", label: "Accensione", Icon: Power },
  { value: "fa-plug", label: "Connettore", Icon: Plug },
  { value: "fa-terminal", label: "Terminale", Icon: Terminal },
  { value: "fa-code", label: "Codice", Icon: Code2 },
  { value: "fa-box", label: "Scatola", Icon: Box },
  { value: "fa-cube", label: "Pacchetto", Icon: Package },
  { value: "fa-warehouse", label: "Archivio fisico", Icon: Warehouse },
  { value: "fa-house", label: "Home", Icon: House },
  { value: "fa-building", label: "Edificio", Icon: Building2 },
  { value: "fa-rocket", label: "Avvio", Icon: Rocket },
  { value: "fa-book", label: "Manuale", Icon: BookOpen },
  { value: "fa-graduation-cap", label: "Formazione", Icon: GraduationCap },
  { value: "fa-briefcase", label: "Lavoro", Icon: BriefcaseBusiness },
  { value: "fa-print", label: "Stampa", Icon: Printer },
];

const iconSuggestions = iconOptions.map((option) => option.value);

const iconColorPresets = ["#6B7280", "#EF4444", "#F59E0B", "#EAB308", "#22C55E", "#10B981", "#14B8A6", "#3B82F6", "#6366F1", "#8B5CF6", "#EC4899", "#F43F5E"];

export { iconColorPresets, iconOptions, iconSuggestions };
